[package]
name = "kernel-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kernel-core = { workspace = true }
bevy_ecs = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
anyhow = { workspace = true }
lyon = "1.0"
cosmic-text = "0.12"
etagere = "0.2"
