//! dxf_export — write a tessellated `Scene` back out as a DXF R2013 (AC1027)
//! textual file.
//!
//! Rationale: the DWG binary-write format is a large undertaking (multi-week
//! effort to match Autodesk's encryption + CRC'd bit-level layout). DXF on
//! the other hand is a plain-text, well-documented group/value pair format
//! that every CAD system on the planet reads (AutoCAD, BricsCAD, QCAD,
//! LibreCAD, Revit, Rhino, Inkscape, …). Writing the user-edited Scene back
//! as DXF unblocks "Save As" immediately; DWG write can be added later as a
//! separate project without re-doing this work.
//!
//! Public surface:
//!   - [`write_dxf`] — encode a [`Scene`] to any `std::io::Write` sink.
//!
//! Output structure (per Autodesk DXF reference, 2013 edition, sections
//! HEADER / TABLES / ENTITIES):
//!
//! ```text
//!   0         999
//! SECTION      Generated by Open 2D Studio (code-999 comment)
//!   2         ...
//! HEADER      (HEADER vars: $ACADVER, $PROJECTNAME, $LASTSAVEDBY,
//!             $EXTMIN, $EXTMAX, $INSUNITS, $CLAYER)
//!   0
//! ENDSEC
//!   0
//! SECTION
//!   2
//! TABLES
//!   0
//! TABLE
//!   2
//! LAYER
//!   (one LAYER record per `scene.layer_names[i]`, color from
//!    `scene.layer_colors[i]` round-tripped to ACI)
//!   0
//! ENDTAB
//!   0
//! ENDSEC
//!   0
//! SECTION
//!   2
//! ENTITIES
//!   (LINE for every Segment, SOLID for every Triangle)
//!   0
//! ENDSEC
//!   0
//! EOF
//! ```
//!
//! Identity tags (so downstream tools recognise the producer):
//!   - `999` comment at top-of-file: `Generated by Open 2D Studio`
//!   - `$PROJECTNAME` header variable = "Open 2D Studio"
//!   - `$LASTSAVEDBY` header variable = "Open 2D Studio"
//!
//! Entity mapping per DXF reference (AcDbEntity common fields):
//!   * LINE   — subclass `AcDbLine`, codes 10/20 start, 11/21 end, 8 layer, 62 color
//!   * SOLID  — subclass `AcDbTrace`, four corners 10/20, 11/21, 12/22, 13/23
//!             (DXF SOLID paints a quad; a degenerate 4th corner equal to the
//!             3rd renders as a filled triangle — standard DXF idiom)
//!
//! Each entity carries a monotonically-increasing handle (code 5, hex) as
//! required by AutoCAD's "Handles Enabled" default since R13.
//!
//! Features intentionally NOT emitted (caller can still read our output in
//! any CAD app; we just don't round-trip these constructs back to named
//! DXF objects — they are already flattened into segments/triangles in the
//! in-memory Scene):
//!   - VIEWPORTs (paper/model duality is squashed; we write all geometry
//!     at world coords)
//!   - BLOCK / INSERT hierarchy (INSERTs are expanded during `load_dxf`)
//!   - HATCH as pattern (solid-fill hatches are already tessellated into
//!     triangles; pattern hatches into dashed line-segments)
//!   - DIMENSION (read as constituent lines + ticks + MTEXT glyphs)
//!   - MTEXT / TEXT (already tessellated into stroke-font segments and/or
//!     TTF-outline triangles in scene_io)

use crate::scene_io::Scene;
use std::collections::HashSet;
use std::io::{self, Write};
use std::time::SystemTime;

/// Current wall-clock time expressed as a Julian-day-fraction double,
/// the format AutoCAD expects in `$TDCREATE` / `$TDUPDATE` (group 40).
///
/// Conversion: Unix epoch (1970-01-01 00:00:00 UTC) = JD 2440587.5.
/// Each second adds `1.0 / 86400.0` JD. We round to ten decimals on
/// emit so the formatted value mirrors AutoCAD's typical precision.
///
/// On a clock-skew error from `SystemTime::now()` we return the Unix
/// epoch JD verbatim -- some auditors require the var to be present
/// and parseable as a finite double, so we never want to skip it.
fn julian_day_now() -> f64 {
    const JD_UNIX_EPOCH: f64 = 2440587.5;
    let secs = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .map(|d| d.as_secs_f64())
        .unwrap_or(0.0);
    JD_UNIX_EPOCH + secs / 86400.0
}

/// Write `scene` to `out` as a DXF R2013 (AC1027) textual file.
///
/// Convenience wrapper around [`write_dxf_filtered`] with no
/// deleted layers — emits every segment / triangle.
pub fn write_dxf<W: Write>(scene: &Scene, out: W) -> io::Result<()> {
    write_dxf_filtered(scene, out, &HashSet::new())
}

/// Like [`write_dxf`] but skips every segment / triangle whose layer
/// name appears in `deleted_layers`. The matching LAYER table records
/// are also dropped so re-loaded files don't re-introduce empty layers.
///
/// Does NOT flush or close `out`. Caller owns the sink (commonly a
/// `BufWriter<File>` — wrap if needed for large scenes).
pub fn write_dxf_filtered<W: Write>(
    scene: &Scene,
    mut out: W,
    deleted_layers: &HashSet<String>,
) -> io::Result<()> {
    // Pre-computed parallel array: is layer-idx i in deleted_layers?
    // O(1) per-entity skip check (vs hashing the layer name N times).
    let is_deleted_layer_idx: Vec<bool> = scene
        .layer_names
        .iter()
        .map(|n| deleted_layers.contains(n))
        .collect();
    let layer_idx_deleted = |li: u16| -> bool {
        is_deleted_layer_idx
            .get(li as usize)
            .copied()
            .unwrap_or(false)
    };
    // Track next handle (code 5) — hex, starts at 20 so it doesn't collide
    // with reserved low handles some readers expect (LAYER 0, BLOCK *Model_Space
    // etc. typically sit in range 1-1F). We pass a `&mut u64` through and let
    // callees bump it — a closure would conflict with `write_layer(&mut handle)`.
    let mut handle: u64 = 0x20;

    // ---- Leading 999-comment block ---------------------------------
    // Code 999 in DXF is a comment record -- silently ignored by every
    // conforming reader (AutoCAD, ODA, libdxfrw, dxf-rs ...). We use it
    // to surface a clear, legal-safe "generator" tag so downstream
    // tools (audit logs, archive ingest pipelines) can tell exactly
    // which application produced the file.
    //
    // CRITICAL: this string MUST NOT claim Autodesk or any other
    // vendor as the generator -- the file is produced by a clean-room
    // implementation that is not affiliated with Autodesk. Even though
    // DXF (text) is not covered by Autodesk's TrustedDWG watermark,
    // mis-attributing the generator is a separate trademark concern.
    writeln!(out, "999")?;
    writeln!(out, "Generated by Open 2D Studio v{} (https://github.com/OpenAEC-Foundation/open-2d-studio)",
        env!("CARGO_PKG_VERSION"))?;
    writeln!(out, "999")?;
    writeln!(out, "DXF R2013 (AC1027) textual export")?;
    writeln!(out, "999")?;
    writeln!(out, "Clean-room implementation -- not affiliated with Autodesk")?;

    // ---- HEADER --------------------------------------------------------
    writeln!(out, "  0\nSECTION")?;
    writeln!(out, "  2\nHEADER")?;

    // Version
    writeln!(out, "  9\n$ACADVER")?;
    writeln!(out, "  1\nAC1027")?;
    // Code page -- ANSI_1252 is the default AutoCAD uses since R14.
    // Our writer emits ASCII-only text (no multibyte glyphs), so this
    // is essentially documentation, but downstream tools occasionally
    // refuse to parse a file without it.
    writeln!(out, "  9\n$DWGCODEPAGE")?;
    writeln!(out, "  3\nANSI_1252")?;
    // Producer identity (two places so any header-inspecting tool sees it)
    writeln!(out, "  9\n$PROJECTNAME")?;
    writeln!(out, "  1\nOpen 2D Studio")?;
    writeln!(out, "  9\n$LASTSAVEDBY")?;
    writeln!(out, "  1\nOpen 2D Studio")?;
    // Units — 0 = unitless; scenes are already in drawing-units from source.
    writeln!(out, "  9\n$INSUNITS")?;
    writeln!(out, " 70\n     0")?;
    // Current layer — always "0" (layer 0 always exists in every DXF).
    writeln!(out, "  9\n$CLAYER")?;
    writeln!(out, "  8\n0")?;
    // $TDCREATE -- file creation timestamp in Julian-day-fraction form
    // (group 40). AutoCAD parses this as a double; we compute the
    // current wall-clock time, convert UNIX-epoch seconds to a Julian
    // day and emit it. If `SystemTime::now()` somehow returns an error
    // we fall back to the Unix epoch (2440587.5 Julian) rather than
    // skip the var -- some auditors require it to be present.
    let jd_create = julian_day_now();
    writeln!(out, "  9\n$TDCREATE")?;
    writeln!(out, " 40\n{:.10}", jd_create)?;
    writeln!(out, "  9\n$TDUPDATE")?;
    writeln!(out, " 40\n{:.10}", jd_create)?;

    // Drawing extents. Scene.bbox is [xmin, ymin, xmax, ymax]. If the
    // scene is empty we emit a tiny default so $EXTMIN < $EXTMAX.
    let (xmin, ymin, xmax, ymax) = {
        let b = scene.bbox;
        if b[0].is_finite() && b[2].is_finite() && b[2] > b[0] {
            (b[0], b[1], b[2], b[3])
        } else {
            (0.0, 0.0, 1.0, 1.0)
        }
    };
    writeln!(out, "  9\n$EXTMIN")?;
    writeln!(out, " 10\n{:.6}", xmin)?;
    writeln!(out, " 20\n{:.6}", ymin)?;
    writeln!(out, " 30\n0.0")?;
    writeln!(out, "  9\n$EXTMAX")?;
    writeln!(out, " 10\n{:.6}", xmax)?;
    writeln!(out, " 20\n{:.6}", ymax)?;
    writeln!(out, " 30\n0.0")?;

    writeln!(out, "  0\nENDSEC")?;

    // ---- TABLES (LAYER only) ------------------------------------------
    writeln!(out, "  0\nSECTION")?;
    writeln!(out, "  2\nTABLES")?;
    writeln!(out, "  0\nTABLE")?;
    writeln!(out, "  2\nLAYER")?;
    writeln!(out, "  5\n{:X}", { let h = handle; handle += 1; h })?;
    writeln!(out, "100\nAcDbSymbolTable")?;
    // Max # of records (code 70) — informational; readers don't enforce.
    let layer_count = scene.layer_names.len().max(1);
    writeln!(out, " 70\n{:>6}", layer_count)?;

    if scene.layer_names.is_empty() {
        // Fallback: always emit layer "0" so ENTITIES references resolve.
        write_layer(&mut out, &mut handle, "0", 7)?;
    } else {
        for (i, name) in scene.layer_names.iter().enumerate() {
            // Drop deleted-layer table records so re-loaded files
            // don't re-introduce the (now empty) layer.
            if layer_idx_deleted(i as u16) { continue; }
            let rgba = scene.layer_colors.get(i).copied().unwrap_or(0xFFFFFFFF);
            let aci = rgba_to_aci(rgba);
            // DXF layer names must be non-empty — substitute "0" if we
            // somehow picked up an empty name during scene load.
            let safe_name = if name.is_empty() { "0" } else { name.as_str() };
            write_layer(&mut out, &mut handle, safe_name, aci)?;
        }
    }

    writeln!(out, "  0\nENDTAB")?;
    writeln!(out, "  0\nENDSEC")?;

    // ---- ENTITIES ------------------------------------------------------
    writeln!(out, "  0\nSECTION")?;
    writeln!(out, "  2\nENTITIES")?;

    // LINE entities ------------------------------------------------------
    for (i, seg) in scene.segments.iter().enumerate() {
        // Skip paper-space segments — most readers treat a DXF without a
        // Layouts dictionary as model-only, and mixing is_paper coords
        // with model coords in one namespace would overlap the drawing.
        // (If we gain Layout writing later, revisit this.)
        if seg.is_paper { continue; }
        // Drop entities on user-deleted layers so saves are clean.
        if let Some(&li) = scene.segment_layer_idx.get(i) {
            if layer_idx_deleted(li) { continue; }
        }

        let layer = layer_name_for(scene, scene.segment_layer_idx.get(i).copied());
        let aci = rgba_to_aci(seg.color);

        writeln!(out, "  0\nLINE")?;
        writeln!(out, "  5\n{:X}", { let h = handle; handle += 1; h })?;
        writeln!(out, "100\nAcDbEntity")?;
        writeln!(out, "  8\n{}", layer)?;
        if aci != 256 {
            writeln!(out, " 62\n{:>6}", aci)?;
        }
        writeln!(out, "100\nAcDbLine")?;
        writeln!(out, " 10\n{:.6}", seg.p1[0])?;
        writeln!(out, " 20\n{:.6}", seg.p1[1])?;
        writeln!(out, " 30\n0.0")?;
        writeln!(out, " 11\n{:.6}", seg.p2[0])?;
        writeln!(out, " 21\n{:.6}", seg.p2[1])?;
        writeln!(out, " 31\n0.0")?;
    }

    // SOLID entities -----------------------------------------------------
    //
    // DXF SOLID (AcDbTrace) fills a quadrilateral defined by four corners.
    // Note the non-intuitive ordering: corners 3 and 4 swap — DXF expects
    // bowtie-order (1,2,4,3). A filled triangle is emitted with corner 4
    // == corner 3.
    for (i, tri) in scene.triangles.iter().enumerate() {
        if tri.is_paper { continue; }
        if let Some(&li) = scene.triangle_layer_idx.get(i) {
            if layer_idx_deleted(li) { continue; }
        }

        let layer = layer_name_for(scene, scene.triangle_layer_idx.get(i).copied());
        let aci = rgba_to_aci(tri.color);

        writeln!(out, "  0\nSOLID")?;
        writeln!(out, "  5\n{:X}", { let h = handle; handle += 1; h })?;
        writeln!(out, "100\nAcDbEntity")?;
        writeln!(out, "  8\n{}", layer)?;
        if aci != 256 {
            writeln!(out, " 62\n{:>6}", aci)?;
        }
        writeln!(out, "100\nAcDbTrace")?;
        // Corner 1
        writeln!(out, " 10\n{:.6}", tri.v[0][0])?;
        writeln!(out, " 20\n{:.6}", tri.v[0][1])?;
        writeln!(out, " 30\n0.0")?;
        // Corner 2
        writeln!(out, " 11\n{:.6}", tri.v[1][0])?;
        writeln!(out, " 21\n{:.6}", tri.v[1][1])?;
        writeln!(out, " 31\n0.0")?;
        // Corner 3
        writeln!(out, " 12\n{:.6}", tri.v[2][0])?;
        writeln!(out, " 22\n{:.6}", tri.v[2][1])?;
        writeln!(out, " 32\n0.0")?;
        // Corner 4 (= corner 3 for a triangle)
        writeln!(out, " 13\n{:.6}", tri.v[2][0])?;
        writeln!(out, " 23\n{:.6}", tri.v[2][1])?;
        writeln!(out, " 33\n0.0")?;
    }

    writeln!(out, "  0\nENDSEC")?;

    // ---- EOF -----------------------------------------------------------
    writeln!(out, "  0\nEOF")?;
    Ok(())
}

/// Emit one `LAYER` table record.
///
/// Per Autodesk DXF reference, LAYER records need: subclass marker
/// `AcDbLayerTableRecord`, name (2), flags (70), color ACI (62), linetype
/// (6). Handles (code 5) are maintained by the caller.
fn write_layer<W: Write>(
    out: &mut W,
    handle: &mut u64,
    name: &str,
    aci: i16,
) -> io::Result<()> {
    writeln!(out, "  0\nLAYER")?;
    writeln!(out, "  5\n{:X}", *handle)?;
    *handle += 1;
    writeln!(out, "100\nAcDbSymbolTableRecord")?;
    writeln!(out, "100\nAcDbLayerTableRecord")?;
    writeln!(out, "  2\n{}", name)?;
    // Flags 70 = 0 (visible, thawed, unlocked).
    writeln!(out, " 70\n     0")?;
    writeln!(out, " 62\n{:>6}", aci)?;
    writeln!(out, "  6\nContinuous")?;
    Ok(())
}

/// Resolve the layer-name string from a `(segment|triangle)_layer_idx` slot.
/// Falls back to "0" when the index is missing or out of range.
fn layer_name_for(scene: &Scene, idx: Option<u16>) -> String {
    match idx {
        Some(i) => scene
            .layer_names
            .get(i as usize)
            .cloned()
            .unwrap_or_else(|| "0".to_string()),
        None => "0".to_string(),
    }
}

/// Approximate round-trip from a packed RGBA u32 (0xAABBGGRR, project
/// convention — see scene_io::aci_to_rgba) to the best matching AutoCAD
/// Color Index.
///
/// This is the inverse of `aci_to_rgba` but lossy — the HSV wheel for
/// ACI 10-249 is quantised, so arbitrary RGB values don't map to exact
/// ACI indices. We match the nine "named" ACI colors exactly (1..=9) and
/// return 7 (white, maps to black on white paper) for anything else. A
/// value of 0 (BYBLOCK / BYLAYER) round-trips to 256 (BYLAYER) which is
/// the usual intent when writing entities.
fn rgba_to_aci(rgba: u32) -> i16 {
    match rgba {
        0 => 256,               // unset / BYLAYER
        0xFF0000FF => 1,        // red
        0xFF00FFFF => 2,        // yellow
        0xFF00FF00 => 3,        // green
        0xFFFFFF00 => 4,        // cyan
        0xFFFF0000 => 5,        // blue
        0xFFFF00FF => 6,        // magenta
        0xFFFFFFFF => 7,        // white/black
        0xFF555555 => 8,        // dark grey
        0xFFAAAAAA => 9,        // light grey
        _ => {
            // Best-effort: strip alpha, find nearest of the 9 named colors
            // by squared RGB distance.
            let a = rgba & 0xFF000000;
            if a == 0 { return 256; }
            let b = ((rgba >> 16) & 0xFF) as i32;
            let g = ((rgba >> 8) & 0xFF) as i32;
            let r = (rgba & 0xFF) as i32;
            let candidates: [(i16, i32, i32, i32); 9] = [
                (1, 255, 0, 0),
                (2, 255, 255, 0),
                (3, 0, 255, 0),
                (4, 0, 255, 255),
                (5, 0, 0, 255),
                (6, 255, 0, 255),
                (7, 255, 255, 255),
                (8, 85, 85, 85),
                (9, 170, 170, 170),
            ];
            let mut best = (7i16, i32::MAX);
            for (aci, cr, cg, cb) in candidates {
                let dr = r - cr;
                let dg = g - cg;
                let db = b - cb;
                let d = dr * dr + dg * dg + db * db;
                if d < best.1 { best = (aci, d); }
            }
            best.0
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scene_io::{Scene, Segment, Triangle, TriKind};

    fn mk_scene() -> Scene {
        let mut s = Scene::empty("test", "test".into());
        s.bbox = [0.0, 0.0, 10.0, 10.0];
        s.layer_names.push("0".into());
        s.layer_colors.push(0xFFFFFFFF);
        s.layer_names.push("wall".into());
        s.layer_colors.push(0xFF0000FF); // red
        s.segments.push(Segment { p1: [0.0, 0.0], p2: [10.0, 10.0], color: 0xFF00FF00, is_paper: false });
        s.segment_layer_idx.push(1);
        s.segment_entity_idx.push(0);
        s.triangles.push(Triangle {
            v: [[0.0, 0.0], [5.0, 0.0], [0.0, 5.0]],
            color: 0xFFD0D0D0,
            is_paper: false,
            kind: TriKind::Solid,
        });
        s.triangle_layer_idx.push(0);
        s.triangle_entity_idx.push(0);
        s.entity_names.push("test-entity".into());
        s
    }

    #[test]
    fn emits_producer_tag() {
        let scene = mk_scene();
        let mut buf: Vec<u8> = Vec::new();
        write_dxf(&scene, &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("Open 2D Studio"), "producer tag missing in header");
        assert!(s.contains("$PROJECTNAME"), "PROJECTNAME var missing");
        assert!(s.contains("$LASTSAVEDBY"), "LASTSAVEDBY var missing");
        assert!(s.contains("AC1027"), "ACADVER missing");
    }

    #[test]
    fn emits_section_structure() {
        let scene = mk_scene();
        let mut buf: Vec<u8> = Vec::new();
        write_dxf(&scene, &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("SECTION"));
        assert!(s.contains("HEADER"));
        assert!(s.contains("TABLES"));
        assert!(s.contains("LAYER"));
        assert!(s.contains("ENTITIES"));
        assert!(s.trim_end().ends_with("EOF"));
    }

    #[test]
    fn emits_line_and_solid() {
        let scene = mk_scene();
        let mut buf: Vec<u8> = Vec::new();
        write_dxf(&scene, &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("\nLINE\n"));
        assert!(s.contains("\nSOLID\n"));
        assert!(s.contains("AcDbLine"));
        assert!(s.contains("AcDbTrace"));
    }

    #[test]
    fn rgba_roundtrip_named_colors() {
        assert_eq!(rgba_to_aci(0xFF0000FF), 1);
        assert_eq!(rgba_to_aci(0xFF00FF00), 3);
        assert_eq!(rgba_to_aci(0xFFFFFFFF), 7);
        assert_eq!(rgba_to_aci(0), 256);
    }
}
